"""
/***************************************************************************
 MappyDockWidget
                                 A QGIS plugin
 helper for consistent goelogical map generation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Luca Penasa, PLANMAP and GMAP team
        email                : luca.penasa@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

import numpy as np
from qgis.PyQt import QtWidgets, uic, QtCore
from qgis.PyQt.QtCore import pyqtSignal
from qgis._core import QgsMessageLog
from qgis.gui import QgsFieldComboBox
from qgis.core import (
    QgsProject,
    QgsMapLayerProxyModel,
    QgsVectorLayer,
    Qgis,
)

from .log_helper import log

# log.getLogger().setLevel(log.DEBUG)

from pathlib import Path


# from qgis.gui import QgsMapLayerComboBox
from mappy.mappy_utils import (
    getChangeSignal,
    is_dev_mode,
    parameters_widgets,
    readWidgetContent,
    serialize_value_for_settings,
)

# Dock widgets that expose still-experimental functionality (currently just
# the incremental engine) -- kept hidden and out of reach of restoreSettingsFromProject
# unless MAPPY_DEV is set, so a generic user can't stumble into them via the
# GUI or via opening a project a developer saved with them enabled.
DEV_ONLY_WIDGET_NAMES = (
    "use_incremental_engine",
    "label_use_incremental_engine_detail",
    "label_topology_tolerance",
    "topology_tolerance",
)

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "qgismappy_dockwidget_base.ui"))


class MappyDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()
    linesLayerChanged = pyqtSignal(QgsVectorLayer)
    pointsLayerChanged = pyqtSignal(QgsVectorLayer)

    def __init__(self, parent=None):
        """Constructor."""

        super().__init__(parent)

        self.setupUi(self)
        self.log_message("Initializing Mappy")
        self.initConstruct()
        self._apply_dev_mode_visibility()

        self.units_field.setLayer(self.points.currentLayer())
        # while true, value_changed() must not write to the project: a
        # project (re)load fires spurious layerChanged signals as the layer
        # combos are cleared and repopulated -- e.g. auto-deselecting to
        # None on QgsProject.clear(), then auto-selecting whatever layer
        # streams in first -- and each one used to get written straight
        # into the project's own "mappy/<name>" entry, clobbering the value
        # just loaded from the project file before restoreSettingsFromProject
        # ever got to read it back (see test_restore_multiple_layers.py and
        # the "limits layer reverts to the first layer on reload" report)
        self._restoring_from_project = False
        self.restoreSettingsFromProject()

        proj = QgsProject.instance()
        proj.cleared.connect(self._begin_restore_guard)
        proj.readProject.connect(self.restoreSettingsFromProject)
        proj.writeProject.connect(self.saveSettingsToProject)

        self.infobox.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.infobox.setOpenExternalLinks(True)

        self.connect_widgets()

    def _apply_dev_mode_visibility(self):
        """Hides the experimental-feature widgets (see DEV_ONLY_WIDGET_NAMES)
        unless MAPPY_DEV is set. They stay in the .ui/dataclass as normal --
        this only keeps them out of a generic user's view.

        The "Experimental" group box currently holds nothing but these
        dev-only widgets, so it's hidden right along with them -- a
        generic user would otherwise see an empty, pointless group box.
        """
        dev = is_dev_mode()
        for name in DEV_ONLY_WIDGET_NAMES:
            self.get_widget_by_name(name).setVisible(dev)
        self.groupBox_experimental.setVisible(dev)

    def get_available_settings(self):
        settings = []
        for name in self.__dict__.copy():
            w = getattr(self, name)

            if type(w) in parameters_widgets:
                settings.append(name)

    def get_widget_by_name(self, name):
        return getattr(self, name)

    def get_current_parameter_value(self, name):
        w = self.get_widget_by_name(name)
        return readWidgetContent(w)

    def connect_widgets(self):
        for name in self.__dict__.copy():
            w = getattr(self, name)

            wtype = type(w)
            if wtype not in parameters_widgets:
                continue

            # A plain closure bound to this instance only -- no shared
            # state on self.__class__. The previous approach dynamically
            # setattr'd a same-named method onto the (shared!) class on
            # every dock construction, so a second dock instance would
            # silently replace the method an earlier, still-live dock's
            # widget signal was connected to. That is suspected to be
            # behind a PyQt5-only segfault reproduced in Docker (see
            # test_new_dock_reloads_settings_already_in_project_at_construction):
            # constructing (and even properly deleting) a second
            # MappyDockWidget corrupted a later signal emission on the
            # first, still-alive dock's checkbox.
            def make_slot(name):
                def slot(value):
                    self.value_changed(name, value)

                return slot

            s = getChangeSignal(w)
            s.connect(make_slot(name))

    def value_changed(self, name, value):
        print(value)
        log.debug("--------------------------------------------------------------")
        log.debug(f"Detected parameter change in {name} to value {type(value)}")

        proj = QgsProject.instance()

        if name == "points":
            log.debug("points layer was changed")
            points_layer = serialize_value_for_settings(value)
            key = points_layer + "_preferred_field"
            log.debug("reading from settings")
            suggested, good = proj.readEntry("mappy", key)
            log.debug(f"suggested value {suggested}")
            # setLayer() below makes the field combo auto-pick a default field,
            # which re-enters value_changed("units_field", ...) synchronously and
            # would overwrite the stored preference above if read afterwards
            self.units_field.setLayer(value)
            if good:
                self.units_field: QgsFieldComboBox
                exists = self.units_field.findText(suggested)
                log.debug(exists)
                if suggested and exists:
                    log.debug("----> set back field to previsouly used assignement")
                    self.units_field.setField(suggested)

            self.pointsLayerChanged.emit(value)

        if name == "lines":
            self.linesLayerChanged.emit(value)

        if name == "units_field":
            # we store also this preference for being connected to this specific layer of points
            points_layer = serialize_value_for_settings(self.get_current_parameter_value("points"))
            key = points_layer + "_preferred_field"
            if not self._restoring_from_project:
                proj.writeEntry("mappy", key, value)
                log.debug(f"stored preference with value {value} to key {key}")

        current = self.get_current_parameter_value(name)
        log.debug(f"CURRENT VALUE {current}")

        if self._restoring_from_project:
            # a project (re)load is in flight: layer combos fire spurious
            # layerChanged signals of their own accord while they get
            # cleared and repopulated (auto-deselecting to None, then
            # auto-selecting whichever layer streams in first), well before
            # restoreSettingsFromProject() gets a chance to apply the value
            # actually saved in the project file. Writing those transient
            # values back here would clobber that saved entry before it is
            # ever read, so skip persisting until the restore is done.
            log.debug("Restoring from project -- not writing transient value to settings")
            return

        asstring = serialize_value_for_settings(value)

        proj.writeEntry("mappy", name, asstring)
        log.debug("Wrote to settings")

    def saveSettingsToProject(self, *args):
        """Write every current widget value to the project, regardless of
        whether each one individually went through value_changed() since the
        project was last loaded. Connected to QgsProject.writeProject so the
        dock's current state is always captured on save, not just on change.
        """
        log.debug("Saving all current dock settings to project")

        proj = QgsProject.instance()

        from .mappy_utils import collect_parameters

        pars = collect_parameters(self)
        for name, value in pars.items():
            asstring = serialize_value_for_settings(value)
            proj.writeEntry("mappy", name, asstring)

        log.debug(f"Saved pars {pars}")

    def _begin_restore_guard(self):
        """Connected to QgsProject.cleared, which fires at the very start of
        both "Open Project" and "New Project" -- well before readProject (if
        it fires at all) triggers restoreSettingsFromProject(). Layer combos
        emit spurious layerChanged signals of their own accord as they get
        cleared and repopulated in between, so the guard must start here,
        not just inside restoreSettingsFromProject(), to cover that window
        too. Cleared at the end of restoreSettingsFromProject(); the
        singleShot is a fallback for "New Project", which never emits
        readProject at all and would otherwise leave the guard stuck on.
        """
        self._restoring_from_project = True
        QtCore.QTimer.singleShot(0, self._end_restore_guard)

    def _end_restore_guard(self):
        self._restoring_from_project = False

    def restoreSettingsFromProject(self):

        log.debug("Restoring values from settings")

        proj = QgsProject.instance()

        self._restoring_from_project = True
        try:
            from .mappy_utils import collect_parameters

            pars = collect_parameters(self)
            log.debug(f"found pars {pars}")

            dev = is_dev_mode()

            for k in pars:
                if not dev and k in DEV_ONLY_WIDGET_NAMES:
                    # keep experimental settings at their widget default for a
                    # generic user, even if a dev saved the project with them
                    # enabled -- MAPPY_DEV gates activation, not just visibility
                    continue
                value, found = proj.readEntry("mappy", k, None)
                log.debug(f"just read {k}: {value}")
                if not found:
                    continue
                ptype = type(pars[k])
                if ptype in [str]:
                    pars[k] = value
                elif ptype in [float, np.double]:
                    pars[k] = np.double(value)
                elif ptype in [bool]:
                    # value is always a str here (serialize_value_for_settings
                    # stores everything as str(value)); bool(value) would be
                    # True for the non-empty string "False" too
                    pars[k] = str(value).strip().lower() == "true"
                elif ptype in [QgsVectorLayer]:
                    root = proj.layerTreeRoot()
                    layer_node = root.findLayer(value)
                    # QgsLayerTreeLayer is a leaf node (no children), and falls
                    # back to __len__ for truthiness, which is 0 -- "if layer_node:"
                    # is falsy even when a real node was found, so it must be an
                    # explicit None check
                    if layer_node is not None:
                        pars[k] = layer_node.layer()
                    log.debug(f"found layer {layer_node}")

                else:
                    raise TypeError(f"cannot convert type {type(value)} to {type(pars[k])}")

                from .mappy_utils import restoreWidgetContent

                w = self.get_widget_by_name(k)
                try:
                    restoreWidgetContent(w, pars[k])
                except Exception as e:
                    log.debug(f"Could not restore the value for the widget from the settings.\n Error: {e}")

                if k == "points":
                    # QgsMapLayerComboBox can end up already showing the correct
                    # layer without ever firing layerChanged (e.g. it auto-selects
                    # a project's only point layer on its own), so units_field
                    # would never learn about it through that signal chain -- bind
                    # it explicitly rather than depending on that reentrant call
                    self.units_field.setLayer(self.points.currentLayer())

            log.debug(f"resulting pars {pars}")
        finally:
            self._restoring_from_project = False

    def getUserHome(self):
        return str(Path.home())

    def initConstruct(self):
        self.lines.setFilters(QgsMapLayerProxyModel.LineLayer)
        self.points.setFilters(QgsMapLayerProxyModel.PointLayer)
        home = self.getUserHome()
        initfname = Path(home).joinpath("geomap.gpkg").as_posix()
        self.output.lineEdit().setText(initfname)
        self.output.setFilter("*.gpkg")

    def log_message(self, message, level=Qgis.MessageLevel.Info, notifyUser=True):
        QgsMessageLog.logMessage(message, "Mappy", level, notifyUser)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
