"""
/***************************************************************************
 Mappy
                                 A QGIS plugin
 helper for consistent goelogical map generation
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-06-24
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Luca Penasa, PLANMAP and GMAP team
        email                : luca.penasa@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QUrl
from qgis.PyQt.QtGui import QDesktopServices

from .resources import *  # DO NOT DELETE  # noqa: F403
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from qgis.core import QgsProject, QgsVectorLayer, QgsMessageLog, Qgis


from .mappy_utils import load_mappy_info_text
from .qgismappy_dockwidget import MappyDockWidget
from qgis.core import QgsApplication

from .engine import EngineConfig, EngineError, ProcessingMapEngine
from .providers import MappyProvider
import os.path

from .log_helper import log


class Mappy:
    """QGIS Plugin Implementation."""

    instance = None

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = (QSettings().value("locale/userLocale") or "en")[0:2]
        locale_path = os.path.join(self.plugin_dir, "i18n", f"Mappy_{locale}.qm")

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr("&Mappy")
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar("Mappy")
        self.toolbar.setObjectName("Mappy")

        # print "** INITIALIZING Mappy"

        self.pluginIsActive = False
        self.dockwidget = None

        self.provider = None
        self.info_text = load_mappy_info_text()

        self.assign_unit_tool = None
        self.assign_unit_action = None

        self.quick_draw_line_tool = None
        self.quick_edit_mode_action = None

        self.config_dock = MappyDockWidget()
        self.config_dock.closingPlugin.connect(self.close_config)
        # print(f"setting infobox text to {self.info_text}")
        self.config_dock.infobox.setHtml(self.info_text)
        self.iface.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self.config_dock)

        self.engine = ProcessingMapEngine()
        self.engine.mapRecomputed.connect(lambda: self.log_message("Map recomputed"))
        self.engine.unitAssigned.connect(lambda unit, fid: self.log_message(f"Unit '{unit}' assigned to polygon {fid}"))

        v = self.getVersion()

        self.log_message(f"Mappy version: {v}")

        Mappy.instance = self

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate("Mappy", message)

    def getVersion(self):
        import mappy
        from pathlib import Path

        f = Path(mappy.__file__).parent.joinpath("metadata.txt")
        self.log_message(f"Reading version from  {f}")

        try:
            with open(f) as file:
                for line in file.readlines():
                    if line.startswith("version"):
                        return line.split("=")[1]
        except Exception:
            self.log_message("cannot determine version of mappy")

    def log_message(self, message, level=Qgis.MessageLevel.Info, notifyUser=True):
        QgsMessageLog.logMessage(message, "Mappy", level, notifyUser)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ":/plugins/qgismappy/icons/settings.png"
        self.add_action(
            icon_path, text=self.tr("Toggle Mappy config"), callback=self.toggle_config_dock, parent=self.iface.mainWindow()
        )

        icon_path = ":/plugins/qgismappy/icons/reload.png"
        self.recompute_action = self.add_action(
            icon_path,
            text=self.tr("Recompute map. Will overwrite data, hence pay attention to the config settings."),
            callback=self.recompute_map,
            parent=self.iface.mainWindow(),
        )
        # registerMainWindowAction (rather than a plain setShortcut) is what
        # makes the shortcut show up in Settings > Keyboard Shortcuts and in
        # the toolbar tooltip, and lets the user remap it if it clashes
        self.iface.registerMainWindowAction(self.recompute_action, "Ctrl+Shift+F5")

        icon_path = ":/plugins/qgismappy/icons/assign_unit.png"
        self.assign_unit_action = self.add_action(
            icon_path,
            text=self.tr("Assign unit to polygon"),
            callback=self.toggle_assign_unit_tool,
            parent=self.iface.mainWindow(),
        )
        self.assign_unit_action.setCheckable(True)

        # reuse QGIS's own "Toggle Editing" pencil rather than a custom icon
        icon_path = ":/images/themes/default/mActionToggleEditing.svg"
        self.quick_edit_mode_action = self.add_action(
            icon_path,
            text=self.tr("Quick enable editing"),
            callback=self.trigger_quick_edit_mode,
            parent=self.iface.mainWindow(),
        )
        # self.quick_edit_mode_action.setCheckable(True)

        icon_path = None
        self.add_action(icon_path, text=self.tr("Online Help"), callback=self.openHelp, parent=self.iface.mainWindow())

        self.initProcessing()

    def openHelp(self):
        QDesktopServices.openUrl(QUrl("https://mappy.readthedocs.io"))

    def toggle_config_dock(self):
        if self.config_dock.isVisible():
            self.config_dock.setVisible(False)
        else:
            self.config_dock.setVisible(True)

    def close_config(self):
        self.config_dock.closingPlugin.disconnect(self.close_config)
        pass  # nothing relevant for now

    def check_if_layer_not_none_or_invalid(self, layer: QgsVectorLayer):
        if layer is None:
            status = "None"
        elif not layer.isValid():
            status = "Invalid"
        else:
            status = "ok"

        if status != "ok":
            return False, status
        else:
            return True, status

    def alert_box(self, title, message):
        dlg = QMessageBox()
        dlg.setWindowTitle(title)
        dlg.setText(message)
        return dlg.exec()

    def check_input_pars(self, pars):
        print(pars)
        try:
            lines = pars["lines"]
        except KeyError:
            self.alert_box("Error", "Missing lines layer. Please select it in the settings.")
            return False

        try:
            points = pars["points"]
        except KeyError:
            self.alert_box("Error", "Missing points layer. Please select it in the settings.")
            return False

        # points = pars["points"]
        lines: QgsVectorLayer
        points: QgsVectorLayer
        log.debug("---------->")
        log.debug(lines.sourceCrs().mapUnits())
        log.debug(lines.sourceCrs().mapUnits())

        b, status = self.check_if_layer_not_none_or_invalid(lines)
        if not b:
            self.alert_box(f"Line layer {status}", "The layer is missing or invalid")
            return False

        b, status = self.check_if_layer_not_none_or_invalid(points)
        if not b:
            self.alert_box(f"Line layer {status}", "The layer is missing or invalid")
            return False

        lines_is_mod = lines.isModified()
        points_is_mod = points.isModified()

        layers = ""
        if lines_is_mod:
            layers += "lines"

        if points_is_mod:
            if layers == "":
                layers += "points"
            else:
                layers += " and points"

        if lines.isModified() or points.isModified():
            dlg = QMessageBox()
            dlg.setWindowTitle("Unsaved changes")
            dlg.setText(f'Input layer(s) "{layers}" have unsaved changes. Click ok to save and proceed with map creation')
            dlg.setStandardButtons(QMessageBox.StandardButton.Save | QMessageBox.StandardButton.Cancel)
            button = dlg.exec()

            if button == QMessageBox.StandardButton.Save:
                lines.commitChanges(False)
                points.commitChanges(False)
                return True
            else:
                return False

        return True

    def _refresh_engine_config(self) -> dict:
        """Rebuilds self.engine.config from the dock's current widget
        values, returning the raw pars dict too since check_input_pars
        (GUI-only validation) still needs to read it directly."""
        from .mappy_utils import collect_parameters

        pars = collect_parameters(self.config_dock)
        self.engine.config = EngineConfig.from_parameters(pars)
        return pars

    def recompute_map(self):
        pars = self._refresh_engine_config()

        if not self.check_input_pars(pars):
            return

        try:
            self.engine.recompute_map()
        except EngineError as e:
            self.alert_box("Error", str(e))

    def toggle_assign_unit_tool(self, checked):
        canvas = self.iface.mapCanvas()
        if checked:
            if self.assign_unit_tool is None:
                from .assign_unit_map_tool import AssignUnitMapTool

                self.assign_unit_tool = AssignUnitMapTool(canvas, self)
            canvas.setMapTool(self.assign_unit_tool)
        else:
            canvas.unsetMapTool(self.assign_unit_tool)

    def trigger_quick_edit_mode(self):
        print("trigger_quick_edit_mode")

        from .mappy_utils import collect_parameters

        pars = collect_parameters(self.config_dock)

        line_layer = pars.get("lines")

        if line_layer is None:
            self.alert_box("Error", "Missing lines layer. Please select it in the settings.")
            return

        self.iface.layerTreeView().setCurrentLayer(line_layer)

        if not line_layer.isEditable():
            line_layer.startEditing()

        self.iface.actionAddFeature().trigger()

    def on_assign_unit_tool_deactivated(self):
        if self.assign_unit_action is not None:
            self.assign_unit_action.setChecked(False)

    def assign_unit_at_point(self, point):
        """Called by AssignUnitMapTool with the clicked point (canvas CRS).

        Transforms the click into the polygons layer's CRS and asks the
        engine to find the polygon/indicator point at that location, then
        opens AssignUnitDialog for the user to pick/type a unit name, and
        hands the result to the engine to actually perform the write. A
        full recompute_map() -- which redoes the point/polygon join, dangle
        cleanup, etc. -- only additionally runs if the
        "auto_recompute_on_assign_unit" setting is enabled (off by
        default); otherwise the user is left to trigger it manually.
        """
        from qgis.core import QgsCoordinateTransform

        from .assign_unit_dialog import AssignUnitDialog

        self._refresh_engine_config()

        try:
            polygons_layer = self.engine.get_polygons_layer()
        except EngineError as e:
            self.alert_box("Error", str(e))
            return

        # the click comes in the canvas CRS; both the points and polygons
        # layers are always created with the same CRS by Quick Project Setup,
        # so a single transform into that shared CRS is enough
        canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()
        if canvas_crs != polygons_layer.crs():
            xform = QgsCoordinateTransform(canvas_crs, polygons_layer.crs(), QgsProject.instance())
            point = xform.transform(point)

        matched_polygon = self.engine.find_polygon_at_point(point)
        if matched_polygon is None:
            self.iface.messageBar().pushInfo("Mappy", "No polygon at that location.")
            return

        target_point_feature = self.engine.find_indicator_for_polygon(matched_polygon, near_point=point)
        units_field = self.engine.config.units_field
        current_value = target_point_feature[units_field] if target_point_feature is not None else None

        existing_values = self.engine.list_existing_units()
        current_value_str = str(current_value) if str(current_value) in existing_values else None
        color_table = self.engine.get_color_table()

        text, color, changed_colors, ok = AssignUnitDialog.getUnit(
            self.iface.mainWindow(),
            existing_values,
            current_value_str,
            color_table,
        )

        if not ok or not text:
            return

        self.engine.assign_unit(matched_polygon, target_point_feature, point, text, color=color, changed_colors=changed_colors)

        if not self.engine.config.auto_recompute_on_assign_unit:
            self.iface.messageBar().pushInfo(
                "Mappy",
                "Unit assigned. Recompute the map to update the point/polygon join, dangle cleanup, etc.",
            )

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        self.iface.unregisterMainWindowAction(self.recompute_action)

        for action in self.actions:
            self.iface.removePluginMenu(self.tr("&Mappy"), action)
            self.iface.removeToolBarIcon(action)

        if self.assign_unit_tool is not None:
            self.iface.mapCanvas().unsetMapTool(self.assign_unit_tool)

        # the dock widget stays connected to QgsProject.instance() (a
        # long-lived singleton that outlives plugin reloads) via
        # readProject/writeProject, and stays embedded in the main window
        # unless explicitly removed -- otherwise a reload leaves this old,
        # never-refreshed instance alive and docked alongside the new one
        proj = QgsProject.instance()
        proj.readProject.disconnect(self.config_dock.restoreSettingsFromProject)
        proj.writeProject.disconnect(self.config_dock.saveSettingsToProject)
        self.iface.removeDockWidget(self.config_dock)
        self.config_dock.deleteLater()
        del self.config_dock

        # remove the toolbar
        self.iface.mainWindow().removeToolBar(self.toolbar)
        del self.toolbar

        QgsApplication.processingRegistry().removeProvider(self.provider)

    def initProcessing(self):
        self.provider = MappyProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)
