# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create Release

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
   
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create package
      run: |
        make package
