# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
   
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Install system deps (qgis)
      run: |
        sudo apt-get update
        sudo apt-get install python3-qgis
        
    - name: Install Python additional dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        make tests

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Create package
      run: |
        make package
        cp mappy/zip_build/mappy.zip  mappy/zip_build/mappy-${{ steps.get_version.outputs.VERSION }}.zip




    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          mappy/zip_build/mappy-${{ steps.get_version.outputs.VERSION }}.zip


